### ISSUE TITLE
account registration and account information update failed on wrong ORCID

### ISSUE THREAD

**Issue by lulin-song** [iedadata/sesar#26]
Two users reported that they were not able to set up SESAR account as new user.

**Comment by smrgeoinfo** [comment]
I was able to create a new account just now.

**Comment by smrgeoinfo** [comment]
[from MEgan:] Multiple users have been able to create new accounts in SESAR. Lulin and I have identified the problem. The issue is related specifically to the ORCID field and users trying to add ORCIDs that are longer than 16 characters. ORCID identifiers are 16 characters. Lulin and I are working on this right now.

**Comment by smrgeoinfo** [comment]
Is this resolved?

**Comment by lulin-song** [comment]
Fixed in v7.0.1
